use_frameworks!

target 'Duvel_Tests' do
  pod 'Duvel', :path => '../'

  # The test frameworks
  pod 'Quick',  '~> 0.10'
  pod 'Nimble', '~> 5.0'
end

post_install do |installer|
  # Make sure all targets have the right swift version set
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
